name = "FJsample"
version = "0.2.0"
license = "MIT"
author = "Ryan Bignell"
maintainer = "ryan07bignell+github@gmail.com"
copyright = "Copyright 2025, Ryan Bignell"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = true

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"


[extra.fortitude.check]
ignore = [
       "MOD011",  # allows (/ /)
       "MOD021",  # allows .gt.
#       "C132",    # allows default public accessiblility
#       "E001",    # ignores syntax errors - useful as pre-processor support is tough
       "S241",    # allows strings with single quotes,
#       "C011",    # allows missing default in select case statements       
       ]
preview = true
line-length = 132  # 132 is apparently an implicit standard in compilers?
	      	   # not sure this is actually working here...
[extra.check.per-file-ignores]
"c_wrapper/FJsample_c.f90" = ["C003"]  # f2py doesn't know how to handle implicit none(external)
